export const payPalDonationLink = "https://www.paypal.com/donate/?hosted_button_id=3JYNMMVYD9KC6"
export const facebookURL = "http://facebook.com/globalearthrepair"
export const twitterURL = "https://twitter.com/earthrepairorg"
export const instagramURL = "https://www.instagram.com/globalearthrepair/"
export const youtubeURL = "http://youtube.com/c/globalearthrepair"